name: First interaction greeter
on: [pull_request, issues]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: '# This is your first issue. ğŸ“œ
          #### You seem to have an eye for detail ğŸ”¥.
          
          Hi ğŸ‘‹
          Thank you so much taking the time in opening an issue with us. We hope that this starts an engaging and insightful discussion with the maintainers and community members.
          Replies may sometimes be slow but please be patient as we are all are working to enhance this project together.
          
          Also, we know its uncommon to say this but ''**Happy first issue** ğŸ‰!''.
          
          
          - Megha Simulator Team.'
          pr-message: '# This is your first PR. ğŸš€
          #### Psst! no pressure ğŸ‘.
          
          Hi ğŸ‘‹
          Thank you so much taking the time in opening an PR with us. Your PR will be run against various different tests, code quality checks and operations to make sure everything is alright (Don''t worry we trust that you checked your code, this is just a standard procedure all PRs go through ğŸ˜Š).

          Even if all the tests are successful and the PR has not been merged, it''s mostly because the maintainers have not done or are in the process of performing a final review of your code before approving the merge. If any more changes are required we''ll let you know! (don''t worry we''ll make sure it''s the important changes only ğŸ‘).

          Merges may sometimes be slow but please be patient as we are all are working to enhance this project together.
          
          All the best for your **first PR** ğŸ‰!.
          
          
          - Megha Simulator Team.'
